services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /ssd/docker_registry:/var/lib/registry
      - type: bind
        source: ./config.yaml
        target: /etc/docker/registry/config.yml

